import type { Metadata } from "next";
import { DM_Mono, Barlow_Condensed, Host_Grotesk } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/components/LenisProvider";
import Header from "@/components/layout/header/Header";
import StickyHeader from "@/components/layout/header/StickyHeader";
import GsapRouteAirbag from "@/components/GsapRouteAirbag";

const barlowFont = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-barlow",
  display: "swap"
});

const dmMonoFont = DM_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-dm",
  display: "swap"
});

const hostFont = Host_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-grotesk",
  display: "swap",
  style: "normal"
})

export const metadata: Metadata = {
  title: "HumanDev-Portfolio",
  description: "Generated by create next app",
  icons: "/icon/human-logo.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen overflow-hidden ${barlowFont.variable} ${dmMonoFont.variable} ${hostFont.variable}`}
      >
        <LenisProvider/>
        <GsapRouteAirbag/>
        <Header/>
        {children}
      </body>
    </html>
  );
}
